apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
type: Opaque
stringData:
  mongo-uri: "mongodb+srv://ahmedrizavi04_db_user:SXaiIh7Al6tMUx38@cluster0.bpg5v2e.mongodb.net/todo_app?retryWrites=true&w=majority"